name: Hola mundo
on:
  push:
    branches: [ main ]
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo
      run: |
        echo $MI_VARIABLE.
          echo Add other actions to build,
          echo test, and deploy your project.
